"""
" service name
"""
OBSTACLES_AVOID_SERVICE_NAME = "obstacles_avoid"


"""
" service api version
"""
OBSTACLES_AVOID_API_VERSION = "1.0.0.2"


"""
" api id
"""
OBSTACLES_AVOID_API_ID_SWITCH_SET = 1001
OBSTACLES_AVOID_API_ID_SWITCH_GET = 1002
OBSTACLES_AVOID_API_ID_MOVE = 1003
OBSTACLES_AVOID_API_ID_USE_REMOTE_COMMAND_FROM_API = 1004