"""
" service name
"""
ROBOT_SPORT_SERVICE_NAME = "sport"

"""
" service api version
"""
ROBOT_SPORT_API_VERSION = "1.0.0.1"

"""
" api id
"""
ROBOT_SPORT_API_ID_DAMP = 1001
ROBOT_SPORT_API_ID_BALANCESTAND = 1002
ROBOT_SPORT_API_ID_STOPMOVE = 1003
ROBOT_SPORT_API_ID_STANDUP = 1004
ROBOT_SPORT_API_ID_STANDDOWN = 1005
ROBOT_SPORT_API_ID_RECOVERYSTAND = 1006
ROBOT_SPORT_API_ID_EULER = 1007
ROBOT_SPORT_API_ID_MOVE = 1008
ROBOT_SPORT_API_ID_BODYPOSITION = 1009
ROBOT_SPORT_API_ID_SWITCHGAIT = 1011
ROBOT_SPORT_API_ID_BODYHEIGHT = 1013
ROBOT_SPORT_API_ID_SPEEDLEVEL = 1015
ROBOT_SPORT_API_ID_LEFTSIDEGAIT = 1016
ROBOT_SPORT_API_ID_RIGHTSIDEGAIT = 1017
ROBOT_SPORT_API_ID_HANDSTAND = 1018
ROBOT_SPORT_API_ID_BIPEDSTAND = 1019
ROBOT_SPORT_API_ID_FRONTFLIP = 1020
ROBOT_SPORT_API_ID_BACKFLIP = 1021
ROBOT_SPORT_API_ID_SETAUTORECOVERY = 1040
ROBOT_SPORT_API_ID_SWITCHJOYSTICK = 1041
ROBOT_SPORT_API_ID_GETSTATE = 1034

"""
" error code
"""
# server side
SPORT_ERR_SERVER_OVERTIME = 4201
SPORT_ERR_SERVER_NOT_INIT = 4205
