"""
service name
"""
LOCO_SERVICE_NAME = "sport"

"""
service api version
"""
LOCO_API_VERSION = "1.0.0.0"

"""
api id
"""
ROBOT_API_ID_LOCO_GET_FSM_ID = 7001
ROBOT_API_ID_LOCO_GET_FSM_MODE = 7002
ROBOT_API_ID_LOCO_GET_BALANCE_MODE = 7003
ROBOT_API_ID_LOCO_GET_SWING_HEIGHT = 7004
ROBOT_API_ID_LOCO_GET_STAND_HEIGHT = 7005
ROBOT_API_ID_LOCO_GET_PHASE = 7006  # deprecated
ROBOT_API_ID_LOCO_GET_ARM_SDK_STATUS = 7007
ROBOT_API_ID_LOCO_GET_AVAILABLE_FSM_IDS = 7008

ROBOT_API_ID_LOCO_SET_FSM_ID = 7101
ROBOT_API_ID_LOCO_SET_BALANCE_MODE = 7102
ROBOT_API_ID_LOCO_SET_SWING_HEIGHT = 7103
ROBOT_API_ID_LOCO_SET_STAND_HEIGHT = 7104
ROBOT_API_ID_LOCO_SET_VELOCITY = 7105
ROBOT_API_ID_LOCO_SET_ARM_TASK = 7106
ROBOT_API_ID_LOCO_SET_SPEED_MODE = 7107
ROBOT_API_ID_LOCO_SET_PUNCH_API = 7108
ROBOT_API_ID_LOCO_SET_ARM_SDK_STATUS = 7109

"""
error code
"""
LOCO_ERR_LOCOSTATE_NOT_AVAILABLE = 7301
LOCO_ERR_SCHEDULER_STATE_NOT_AVAILABLE = 7301
LOCO_ERR_INVALID_FSM_ID = 7302
LOCO_ERR_INVALID_TASK_ID = 7303

