"""
" service name
"""
SPORT_SERVICE_NAME = "sport"


"""
" service api version
"""
SPORT_API_VERSION = "1.0.0.1"


"""
" api id
"""
SPORT_API_ID_DAMP              = 1001;
SPORT_API_ID_BALANCESTAND      = 1002;
SPORT_API_ID_STOPMOVE          = 1003;
SPORT_API_ID_STANDUP           = 1004;
SPORT_API_ID_STANDDOWN         = 1005;
SPORT_API_ID_RECOVERYSTAND     = 1006;
SPORT_API_ID_EULER             = 1007;
SPORT_API_ID_MOVE              = 1008;
SPORT_API_ID_SIT               = 1009;
SPORT_API_ID_RISESIT           = 1010;
SPORT_API_ID_SWITCHGAIT        = 1011;
SPORT_API_ID_TRIGGER           = 1012;
SPORT_API_ID_BODYHEIGHT        = 1013;
SPORT_API_ID_FOOTRAISEHEIGHT   = 1014;
SPORT_API_ID_SPEEDLEVEL        = 1015;
SPORT_API_ID_HELLO             = 1016;
SPORT_API_ID_STRETCH           = 1017;
SPORT_API_ID_TRAJECTORYFOLLOW  = 1018;
SPORT_API_ID_CONTINUOUSGAIT    = 1019;
SPORT_API_ID_CONTENT           = 1020;
SPORT_API_ID_WALLOW            = 1021;
SPORT_API_ID_DANCE1            = 1022;
SPORT_API_ID_DANCE2            = 1023;
SPORT_API_ID_GETBODYHEIGHT        = 1024;
SPORT_API_ID_GETFOOTRAISEHEIGHT   = 1025;
SPORT_API_ID_GETSPEEDLEVEL        = 1026;
SPORT_API_ID_SWITCHJOYSTICK       = 1027;
SPORT_API_ID_POSE                 = 1028;
SPORT_API_ID_FRONTJUMP            = 1031;
SPORT_API_ID_ECONOMICGAIT         = 1035;
SPORT_API_ID_MOVETOPOS            = 1036;
SPORT_API_ID_SWITCHEULERMODE    = 1037;
SPORT_API_ID_SWITCHMOVEMODE     = 1038;


"""
" error code
"""
# client side
SPORT_ERR_CLIENT_POINT_PATH = 4101
# server side
SPORT_ERR_SERVER_OVERTIME = 4201
SPORT_ERR_SERVER_NOT_INIT = 4202
