"""
R1 loco service constants.
"""

LOCO_SERVICE_NAME = "sport"
LOCO_API_VERSION = "1.0.0.0"

ROBOT_API_ID_LOCO_GET_FSM_ID = 7001
ROBOT_API_ID_LOCO_GET_FSM_MODE = 7002

ROBOT_API_ID_LOCO_SET_FSM_ID = 7101
ROBOT_API_ID_LOCO_SET_VELOCITY = 7105
ROBOT_API_ID_LOCO_SET_SPEED_MODE = 7107

LOCO_ERR_LOCOSTATE_NOT_AVAILABLE = 7301
LOCO_ERR_SCHEDULER_STATE_NOT_AVAILABLE = 7301
LOCO_ERR_INVALID_FSM_ID = 7302
LOCO_ERR_INVALID_TASK_ID = 7303
LOCO_ERROR_FSM_ID_RETURN_DENIED = 7304
